### ISSUE TITLE
Removing scale drift in VO ?

### ISSUE THREAD

**Issue by saimanoj18** [JzHuai0108/sim3opt#1]
Dear Jianzhu Huai,

I have a doubt.

We have a car with a camera fixed on it. The task is to estimate true to scale 3D poses of the path taken by the car offline. We plan to use it for 3D map construction later.
 
I have used feature matching between frames to estimate visual odometry. I scale the VO with rough scale estimates that I get from homography based scale estimation from planar feature matching. Now the estimated scaled VO is having drift in scale, How to fix this ? I am able to perform loop closure detection and next is to perform loop closure.

While looking across, I found from orbslam and other scale drift aware slam paper that - 

If we perform loop closure with Pose Graph Optimization over Sim(3) then the scale drift can be removed. 

Does this pose graph optimization over Sim(3) remove the scale drift ? Is it correct or am I missing something ?

If so, then with a condition that we find reliable loop closures, monocular camera would be all that is required to solve SLAM problem ?

Thank you,
Sai Manoj

**Comment by JzHuai0108** [comment]
1. If we perform loop closure with Pose Graph Optimization over Sim(3) then the scale drift can be removed. Does this pose graph optimization over Sim(3) remove the scale drift ? Is it correct or am I missing something ?

Yes. The drift in scale can be fixed by the loop closure, but the ambiguity in scale can not be resolved yet.

2. If so, then with a condition that we find reliable loop closures, monocular camera would be all that is required to solve SLAM problem ?

With reliable loop closures, a monocular camera can solve the SLAM problem up to a unknown scale factor. If you also have "rough scale estimates that I get from homography based scale estimation from planar feature matching", then a monocular camera can solve the metric SLAM problem. 

A quick question about your rough scale estimates from homography, as I understand, we need to assume either the translation between the two camera capture positions is known or the coordinates of feature points in the plane are known. Are you taking one of the two assumptions in estimating the scale?

**Comment by saimanoj18** [comment]
Thank you for your answer.

Regarding your question on scale estimation, I am following this paper to estimate scale from feature matches in planar patches. I am detecting akaze features in an ROI defined in the front of the car that mostly falls on planar road.

   I see the results in ORB SLAM version 1 paper. Their SLAM trajectory results after 7 DOF alignment aligns very well with the ground truth. This gave an impression that 7DOF solves scale. Now I get the picture that scale drift would be solved but not scale ambiguity. 

I have a question. Then how come did the ORB SLAM results on all datasets align so well with the ground truth ? 

Did it just happen that ORBSLAM results after loop closure is so close to ground truth ?

Or if the visual odometry is close to real trajectory, then there is high chance that loop closure solves the scale ambiguity too ?

Thank you.

**Comment by JzHuai0108** [comment]
>>Then how come did the ORB SLAM results on all datasets align so well with the ground truth ?

They are using [evaluate_ate_scale](https://github.com/raulmur/evaluate_ate_scale)

>>Did it just happen that ORBSLAM results after loop closure is so close to ground truth ?

It is very unlikely.

>>Or if the visual odometry is close to real trajectory, then there is high chance that loop closure solves the scale ambiguity too ?

By no means.

**Comment by saimanoj18** [comment]
- They are using evaluate_ate_scale -> so they were overcoming the scale ambiguity using this assumption/method ?
 - Do you have any suggestion on how to remove scale ambiguity ? I can get the wheel odometry from the car, however, i am not sure if it will be accurate at the frame level. 
- Is it possible that after 7DOF, we just have to multiply all the camera poses with a single scale factor to scale up the map to true scale. Lets say my wheel odometry says that the car has traversed 10 m in x-direction, then I can scale up the map to match this 10 m distance ? 

Would this give reliable map ? Or we should try using distance between some known objects or size of the objects in the scene ?

Thank you!

**Comment by JzHuai0108** [comment]
>>They are using evaluate_ate_scale -> so they were overcoming the scale ambiguity using this assumption/method ?

I think so.

>>Do you have any suggestion on how to remove scale ambiguity ? I can get the wheel odometry from the car, however, i am not sure if it will be accurate at the frame level.

If you can associate the wheel odometry poses to keyframe poses in the pose graph, you may add the wheel odometry as relative constraints for pairs of keyframes to the pose graph optimization problem over Sim(3). Then the whole trajectory scale is recovered at every edge of the pose graph. If the distances between keyframes are short, the relative constraints from wheel odometry should be very accurate.

>>Is it possible that after 7DOF, we just have to multiply all the camera poses with a single scale factor to scale up the map to true scale. Lets say my wheel odometry says that the car has traversed 10 m in x-direction, then I can scale up the map to match this 10 m distance ?

If your map has very small scale distortions/drifts in every parts, you may do so.

>>Would this give reliable map ? Or we should try using distance between some known objects or size of the objects in the scene ?

However the real SLAM maps up to a scale are usually subject to scale distortions here and there even after correct loop closures. So I would recommend using the relative wheel odometry in optimizing the pose graph to recover the metric scale.

**Comment by saimanoj18** [comment]
Thank you so much for those answers. I will try to add wheel odometry as constraints for pose graph and optimize over Sim(3).

I never had experience in doing pose graph optimization and that too over Sim(3).

Can you point me to some reference code that does pose graph optimization over Sim(3) ? Does your sim3opt does it already ? Can you point me to right reference.

Thank you!

**Comment by JzHuai0108** [comment]
Please see [testDirectSim3Optimization](https://github.com/JzHuai0108/sim3opt/blob/master/kitti_surf.cpp#L542) and [testStepwiseSim3Optimization](https://github.com/JzHuai0108/sim3opt/blob/master/kitti_surf.cpp#L713) for two examples of pose graph optimization over Sim(3).

**Comment by saimanoj18** [comment]
Thank you very much!
